name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点执行（根据时区修改）
  workflow_dispatch:  # 支持手动触发

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout target repository
      uses: actions/checkout@v3
      
    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
    - name: Add upstream remote repository
      run: |
        git remote add upstream https://github.com/snap-one/docs-driverworks-proxyprotocol-relay.git
        git fetch upstream
        
    - name: Sync with upstream (merge upstream's master to your branch)
      run: |
        git checkout main
        git pull upstream main
        
    - name: Check for changes and push
      run: |
        git diff --quiet upstream/main && git push origin main || echo "No changes to sync"

